/// Flutter icons SurahFigure
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SurahFigure
///      fonts:
///       - asset: fonts/SurahFigure.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SurahFigure {
  SurahFigure._();

  static const _kFontFam = 'SurahFigure';
  static const _kFontPkg = null;

  static const IconData fiqur = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
